import test from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { createBotStatusServer, qrToSvg } from '../bot-status.js';
test('QR SVG tiene margen blanco y no incorpora el payload como HTML', () => {
  const svg = qrToSvg('<script>alert(1)</script>');
  assert.match(svg, /viewBox="0 0 \d+ \d+"/);
  assert.match(svg, /fill="white"/);
  assert.match(svg, /shape-rendering="crispEdges"/);
  assert.doesNotMatch(svg, /<script>/);
});
test('QR requiere token, vence y se elimina al autenticar', async t => {
  const client = new EventEmitter();
  let now = 100000;
  const server = createBotStatusServer(client, { token: 'private-test-token', now: () => now });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const url = 'http://127.0.0.1:' + server.address().port;
  const headers = { Authorization: 'Bearer private-test-token' };
  assert.equal((await fetch(url + '/status')).status, 401);
  assert.equal((await fetch(url + '/status', { headers: { Authorization: 'Bearer bad' } })).status, 401);
  assert.equal((await fetch(url + '/health')).status, 200);
  client.emit('qr', 'sample-pairing-code');
  const response = await fetch(url + '/status', { headers });
  assert.match(response.headers.get('cache-control'), /no-store/);
  let data = await response.json();
  assert.equal(data.state, 'QR');
  assert.ok(data.qrSvg);
  now += 60001;
  data = await (await fetch(url + '/status', { headers })).json();
  assert.equal(data.qrSvg, null);
  client.emit('qr', 'scanned-pairing-code');
  client.emit('loading_screen', 20, 'Cargando');
  data = await (await fetch(url + '/status', { headers })).json();
  assert.equal(data.state, 'LOADING');
  assert.equal(data.qrSvg, null);
  client.emit('qr', 'fresh-pairing-code');
  client.emit('authenticated');
  data = await (await fetch(url + '/status', { headers })).json();
  assert.equal(data.state, 'AUTHENTICATED');
  assert.equal(data.qrSvg, null);
  client.emit('ready');
  assert.equal((await (await fetch(url + '/status', { headers })).json()).state, 'READY');
  client.emit('disconnected');
  assert.equal((await (await fetch(url + '/status', { headers })).json()).state, 'DISCONNECTED');
});
