import puppeteer from 'puppeteer';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const base = 'http://localhost:3100';
const browser = await puppeteer.launch({ headless: true });
try {
  const page = await browser.newPage();
  await page.setViewport({ width: 1440, height: 1000 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  assert.equal((await fetch(base + '/api/leads/export')).status, 401);
  assert.equal((await fetch(base + '/api/bot/status')).status, 401);
  await page.goto(base + '/leads', { waitUntil: 'networkidle0' });
  assert.ok(page.url().endsWith('/login'));
  await page.type('[name=username]', 'wrong-user');
  await page.type('[name=password]', 'wrong-password');
  await page.click('button[type=submit], form button');
  await page.waitForSelector('[role=alert]');
  assert.match(await page.$eval('[role=alert]', el => el.textContent), /no son correctos/);
  await page.$eval('[name=username]', el => { el.value = ''; });
  await page.$eval('[name=password]', el => { el.value = ''; });
  await page.type('[name=username]', 'browser-user');
  await page.type('[name=password]', 'browser-test-password');
  await Promise.all([page.waitForNavigation({ waitUntil: 'networkidle0' }), page.click('form button')]);
  assert.equal(new URL(page.url()).pathname, '/');
  const values = await page.$$eval('.stat-value', elements => elements.map(el => el.textContent));
  assert.deepEqual(values, ['56', '30', '15', '10']);
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/dashboard-desktop.png', fullPage: true });
  await page.goto(base + '/leads?status=CONTACTED', { waitUntil: 'networkidle0' });
  assert.equal(await page.$$eval('tbody tr', elements => elements.length), 15);
  await page.goto(base + '/leads?page=2', { waitUntil: 'networkidle0' });
  assert.equal(await page.$$eval('tbody tr', elements => elements.length), 20);
  await page.goto(base + '/leads?q=impossible-search', { waitUntil: 'networkidle0' });
  assert.match(await page.$eval('main', el => el.textContent), /No hay coincidencias/);
  await page.goto(base + '/leads/fixture-1', { waitUntil: 'networkidle0' });
  assert.match(await page.$eval('.chat-history', el => el.textContent), /lista de precios/);
  await page.select('[name=status]', 'CONVERTED');
  await page.click('form button');
  await page.waitForSelector('.form-success');
  await page.reload({ waitUntil: 'networkidle0' });
  assert.equal(await page.$eval('[name=status]', el => el.value), 'CONVERTED');
  await page.goto(base + '/leads/nuevo', { waitUntil: 'networkidle0' });
  await page.type('[name=name]', 'Lead manual de prueba');
  await page.type('[name=phoneNumber]', '+54 9 11 9999 8888');
  await page.click('form button');
  await page.waitForSelector('a[href="/leads/fixture-new"]');
  await page.goto(base + '/configuracion', { waitUntil: 'networkidle0' });
  await page.waitForSelector('.qr-box img');
  assert.equal(await page.$eval('.qr-box img', image => image.complete && image.naturalWidth > 0), true);
  await page.$eval('textarea', el => { el.value = 'Hola {nombre}, seguimos con {producto}.'; });
  await page.click('input[type=checkbox]');
  await page.$$eval('button', buttons => buttons.find(button => button.textContent === 'Guardar preferencias').click());
  await page.waitForFunction(() => localStorage.getItem('nico-auto-refresh') === 'true');
  await page.reload({ waitUntil: 'networkidle0' });
  assert.equal(await page.$eval('textarea', el => el.value), 'Hola {nombre}, seguimos con {producto}.');
  await page.screenshot({ path: 'artifacts/settings-desktop.png', fullPage: true });
  const exportResult = await page.evaluate(async () => {
    const response = await fetch('/api/leads/export?status=CONVERTED');
    return { status: response.status, text: await response.text() };
  });
  assert.equal(exportResult.status, 200);
  assert.match(exportResult.text, /Recuperado/);
  await page.setViewport({ width: 390, height: 844 });
  await page.goto(base + '/leads', { waitUntil: 'networkidle0' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.screenshot({ path: 'artifacts/leads-mobile.png', fullPage: true });
  await page.goto(base + '/configuracion', { waitUntil: 'networkidle0' });
  await page.$$eval('button', buttons => buttons.find(button => button.textContent === 'Cerrar sesión').click());
  await page.waitForFunction(() => location.pathname === '/login');
  await page.goto(base + '/', { waitUntil: 'networkidle0' });
  assert.ok(page.url().endsWith('/login'));
  assert.deepEqual(errors, []);
  console.log('OK: login, protección, contadores >50, filtros, paginación, historial, guardado, alta, QR, preferencias, CSV, móvil y cierre de sesión.');
} finally {
  await browser.close();
}
